name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install LLVM
      run: |
        sudo apt-get update
        sudo apt-get install llvm python3-pip python3-venv
        sudo update-alternatives --install /usr/bin/FileCheck FileCheck /usr/bin/FileCheck-18  1

    - name: Setup python and lit
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip3 install lit

    - name: Cache Stages
      id: cache-stages
      uses: actions/cache@v4
      with:
        path: cache/*
        key: ${{ runner.os }}-stages

    - name: make
      run: make

    - name: make test
      run: |
        source .venv/bin/activate
        make test
